version: "3.3"

services:

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#     - /opt/portainer/data:/data
    deploy:
      labels:
        - "com.df.notify=true"
        - "com.df.scrapePort=9000"
        - "traefik.port=9000"

  watchtower:
    image: v2tec/watchtower
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
