version: "3.3"

networks:
    postgres:
      external: true

services:

    jira:
      image: cptactionhank/atlassian-jira-software:latest
      environment:
        - "CATALINA_OPTS= -Xms256m -Xmx512m"
      networks:
        - postgres
      ports:
        - "8080:8080"
      volumes:
        - /var/atlassian/jira
      deploy:
        labels:
          - "com.df.notify=true"
          - "com.df.scrapePort=8080"
          - "traefik.port=8080"
# mysql data to vloume?
