version: '3.3'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.mydomain.lan'
        gitlab_rails['gitlab_ssh_host'] = 'ssh.gitlab.mydomain.lan'
        gitlab_rails['time_zone'] = 'Europe/Budapest'
    volumes:
      - /etc/gitlab
      - /var/log/gitlab
      - /var/opt/gitlab
      - /var/opt/gitlab/gitlab-rails/shared/registry
    ports:
#      - "80:80"
      - "2222:22"
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:gitlab.mydomain.lan"
        - "traefik.docker.network=gitlab"
    networks:
        - gitlab

networks:
  gitlab:
    external: true
