version: '3.1'
services:
    db1:
      image: cockroachdb/cockroach:v1.0.2
      deploy:
            mode: replicated
            replicas: 1
      ports:
            - 8888:8080
      command: start --advertise-host=cockroach_db1 --logtostderr --insecure
      networks:
            - cockroachdb
      volumes:
            - cockroachdb-1:/cockroach/cockroach-data
    db2:
      image: cockroachdb/cockroach:v1.0.2
      deploy:
         mode: replicated
         replicas: 1
      command: start --advertise-host=cockroach_db2 --join=cockroach_db1:26257 --logtostderr --insecure
      networks:
         - cockroachdb
      volumes:
         - cockroachdb-2:/cockroach/cockroach-data
    db3:
      image: cockroachdb/cockroach:v1.0.2
      deploy:
         mode: replicated
         replicas: 1
      command: start --advertise-host=cockroach_db3 --join=cockroach_db1:26257 --logtostderr --insecure
      networks:
         - cockroachdb
      volumes:
         - cockroachdb-3:/cockroach/cockroach-data
    crdb-proxy:
      image: jowings/crdb-proxy:v1
      deploy:
         mode: global
#         replicas: 1
      ports:
         - 26257:26257
      networks:
         - cockroachdb

networks:
    cockroachdb:
        external: true

volumes:
  cockroachdb-1:
    driver: minio/minfs
    driver_opts:
      endpoint: http://192.168.99.100:9001
      access-key: minio
      secret-key: minio123
      bucket: cockroachdb1
      opts: "uid=1000,gid=1000"
  cockroachdb-2:
    driver: minio/minfs
    driver_opts:
      endpoint: http://192.168.99.100:9001
      access-key: minio
      secret-key: minio123
      bucket: cockroachdb2
      opts: "uid=1000,gid=1000"
  cockroachdb-3:
    driver: minio/minfs
    driver_opts:
      endpoint: http://192.168.99.100:9001
      access-key: minio
      secret-key: minio123
      bucket: cockroachdb3
      opts: "uid=1000,gid=1000"
