version: "3.3"

networks:
    admin-net:
      external: true

services:

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    networks:
      - admin-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#     - /opt/portainer/data:/data
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=9000
        - com.df.servicePath=/#/auth
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:mydomain.lan;PathPrefixStrip:/portainer"
        - "traefik.docker.network=admin-net"
    depends_on:
      - proxy


  watchtower:
    image: v2tec/watchtower
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - admin-net
