#Administrator username and password password

version: '3.3'

services:
  couchbase-master:
    image: couchbase
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    networks:
      - couchdb-net
    deploy:
      replicas: 2

networks:
  couchdb-net:
    driver: overlay
