defaultEntryPoints = ["http", "https"]
[web]
# Port for the status page
address = ":8080"
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/certs/mydomain.lan.crt"
      KeyFile = "/certs/mydomain.lan.key"
[docker]
endpoint = "unix:///var/run/docker.sock"
# default domain
domain = "mydomain.lan"
watch = true
swarmmode = true
[accessLog]
  filePath = "/log/access.log"
traefikLogsFile = "/log/traefik.log"
