version: '3.3'

networks:
    admin-net:
      external: true

volumes:
    data:

secrets:
  mydomain.lan.pem:
    file: ./mydomain.lan.pem
  traefik.toml:
    file: ./traefik.toml


services:

    traefik-ssl:
      image: traefik
      command: -c /dev/null --web --docker --docker.swarmmode --docker.watch --web.metrics.prometheus --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0" --logLevel=INFO --configFile="/run/secrets/traefik.toml"
      networks:
        - admin-net
      ports:
        - "443:443"
        - "80:80"
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
#       - /dockerdata/traefik/log:/log
      deploy:
        mode: global
        labels:
          - "com.df.notify=true"
          - "com.df.scrapePort=8080"
          - "traefik.port=8080"
      secrets:
       - mydomain.lan.pem
       - traefik.toml
