version: "3.3"

networks:
    admin-net:
      external: true

volumes:
    data:

secrets:
  traefik.toml:
    file: ./traefik.toml

services:

    traefik:
      image: traefik:1.4
      command: -c /dev/null --web --docker --docker.swarmmode --docker.watch --docker.domain=mydomain.lan --logLevel=DEBUG
      networks:
        - admin-net
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
#       - /dockerdata/traefik/log:/log
      deploy:
        mode: global
        labels:
          - "com.df.notify=true"
          - "com.df.scrapePort=8080"
          - "traefik.port=8080"
      secrets:
       - traefik.toml
