version: "3.3"

services:
  http:
    image: emilevauge/whoami
    networks:
      - admin-net
    deploy:
      replicas: 3
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/http/
        - com.df.reqPathSearch=/http/
        - com.df.reqPathReplace=/renamed/
        - com.df.serviceDomain=mydomain.lan
        - com.df.port=80
        - com.df.denyHttp=true

networks:
  admin-net:
    external: true
